- jsonKey: name
  label: Name
  sort: 1

- jsonKey: type
  label: Type
  sort: 2
  uiType: Select
  validate:
    defaultValue: "custom"
    options:
      - label: Addon Repository
        value: addon-repository
      - label: Application Repository
        value: application-repository
      - label: Infrastructure Repository
        value: infrastructure-repository
      - label: Policy Repository
        value: policy-repository
      - label: Helm Registry
        value: helm-registry
      - label: Image Registry
        value: image-registry
      - label: Terraform AWS Provider
        value: terraform-aws-provider
      - label: Terraform Cloud Credential
        value: terraform-cloud-credential
      - label: Custom
        value: custom

- jsonKey: data
  label: Data
  sort: 3
  uiType: Group
  conditions:
    - jsonKey: type
      op: "!="
      value: custom
      action: enable
  subParameters:
    - jsonKey: provider
      label: Provider
      uiType: Select
      sort: 1
      style:
        colSpan: 24
      validate:
        defaultValue: ""
        options:
          - label: GitHub
            value: GitHub
      conditions:
        - jsonKey: type
          op: ==
          value: addon-repository
          action: enable
        - jsonKey: type
          op: ==
          value: application-repository
          action: enable
        - jsonKey: type
          op: ==
          value: infrastructure-repository
          action: enable
        - jsonKey: type
          op: ==
          value: policy-repository
          action: enable
    - jsonKey: repository
      label: Repository
      sort: 2
      style:
        colSpan: 24
      conditions:
        - jsonKey: type
          op: ==
          value: addon-repository
          action: enable
        - jsonKey: type
          op: ==
          value: application-repository
          action: enable
        - jsonKey: type
          op: ==
          value: infrastructure-repository
          action: enable
        - jsonKey: type
          op: ==
          value: policy-repository
          action: enable
    - jsonKey: AWS_ACCESS_KEY_ID
      label: AWS_ACCESS_KEY_ID
      sort: 3
      style:
        colSpan: 24
      conditions:
        - jsonKey: type
          op: ==
          value: terraform-aws-provider
          action: enable
    - jsonKey: registry
      label: Registry
      sort: 4
      style:
        colSpan: 24
      conditions:
        - jsonKey: type
          op: ==
          value: helm-registry
          action: enable
        - jsonKey: type
          op: ==
          value: image-registry
          action: enable
    - jsonKey: AWS_DEFAULT_REGION
      label: AWS_DEFAULT_REGION
      sort: 5
      style:
        colSpan: 24
      conditions:
        - jsonKey: type
          op: ==
          value: terraform-aws-provider
          action: enable

- jsonKey: secretData
  label: Secret Data
  sort: 4
  uiType: Group
  conditions:
    - jsonKey: type
      op: "!="
      value: custom
      action: enable
  subParameters:
    - jsonKey: username
      label: username
      style:
        colSpan: 24
      sort: 1
      conditions:
        - jsonKey: type
          op: ==
          value: addon-repository
          action: enable
        - jsonKey: type
          op: ==
          value: application-repository
          action: enable
        - jsonKey: type
          op: ==
          value: infrastructure-repository
          action: enable
        - jsonKey: type
          op: ==
          value: policy-repository
          action: enable
        - jsonKey: type
          op: ==
          value: helm-registry
          action: enable
    - jsonKey: password
      label: Password
      uiType: Password
      style:
        colSpan: 24
      sort: 2
      conditions:
        - jsonKey: type
          op: ==
          value: addon-repository
          action: enable
        - jsonKey: type
          op: ==
          value: application-repository
          action: enable
        - jsonKey: type
          op: ==
          value: infrastructure-repository
          action: enable
        - jsonKey: type
          op: ==
          value: policy-repository
          action: enable
        - jsonKey: type
          op: ==
          value: helm-registry
          action: enable
    - jsonKey: jsonContent
      label: JSON Content
      uiType: K8sObjectsCode
      style:
        colSpan: 24
      sort: 3
      conditions:
        - jsonKey: type
          op: ==
          value: image-registry
          action: enable
        - jsonKey: type
          op: ==
          value: terraform-cloud-credential
          action: enable
    - jsonKey: AWS_SECRET_ACCESS_KEY
      label: AWS_SECRET_ACCESS_KEY
      uiType: Password
      style:
        colSpan: 24
      sort: 4
      conditions:
        - jsonKey: type
          op: ==
          value: terraform-aws-provider
          action: enable

- jsonKey: customData
  label: Custom Data
  sort: 5
  uiType: KV
  style:
    colSpan: 24
  conditions:
    - jsonKey: type
      op: ==
      value: custom
      action: enable

- jsonKey: customSecretData
  label: Custom Secret Data
  sort: 6
  uiType: KV
  style:
    colSpan: 24
  conditions:
    - jsonKey: type
      op: ==
      value: custom
      action: enable
